In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [2]:
df1=pd.read_csv('CAX_LogFacies_Train_File.csv')

In [3]:
df1.corr()

row_id   well_id        GR     label
row_id   1.000000  0.000000  0.173751 -0.048928
well_id  0.000000  1.000000 -0.000752 -0.004136
GR       0.173751 -0.000752  1.000000 -0.494568
label   -0.048928 -0.004136 -0.494568  1.000000

In [3]:
df2=pd.read_csv('CAX_LogFacies_Test_File.csv')

In [5]:
df2.corr()

row_id   well_id        GR
row_id   1.000000  0.000000  0.174813
well_id  0.000000  1.000000 -0.000409
GR       0.174813 -0.000409  1.000000

In [4]:
CAX_LogFacies_Submission_File=pd.read_csv('CAX_LogFacies_Submission_File.csv')

In [7]:
CAX_LogFacies_Submission_File.head()

unique_id  label
0     CAX_0    NaN
1     CAX_1    NaN
2     CAX_2    NaN
3     CAX_3    NaN
4     CAX_4    NaN

In [8]:
CAX_LogFacies_Submission_File.shape

(2200000, 2)

In [9]:
df1.describe(),    df2.describe()

(             row_id       well_id            GR         label
 count  4.400000e+06  4.400000e+06  4.400000e+06  4.400000e+06
 mean   5.495000e+02  1.999500e+03  1.092733e+02  1.184489e+00
 std    3.175426e+02  1.154701e+03  3.424240e+01  1.465016e+00
 min    0.000000e+00  0.000000e+00 -3.181915e+00  0.000000e+00
 25%    2.747500e+02  9.997500e+02  8.179222e+01  0.000000e+00
 50%    5.495000e+02  1.999500e+03  1.203849e+02  0.000000e+00
 75%    8.242500e+02  2.999250e+03  1.347291e+02  2.000000e+00
 max    1.099000e+03  3.999000e+03  1.970614e+02  4.000000e+00,
              row_id       well_id            GR
 count  2.200000e+06  2.200000e+06  2.200000e+06
 mean   5.495000e+02  5.999500e+03  1.094807e+02
 std    3.175426e+02  5.773503e+02  3.424748e+01
 min    0.000000e+00  5.000000e+03 -4.928221e+00
 25%    2.747500e+02  5.499750e+03  8.222292e+01
 50%    5.495000e+02  5.999500e+03  1.205686e+02
 75%    8.242500e+02  6.499250e+03  1.348737e+02
 max    1.099000e+03  6.999000e+03  1.96

In [10]:
df1.info()   , df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4400000 entries, 0 to 4399999
Data columns (total 4 columns):
row_id     int64
well_id    int64
GR         float64
label      int64
dtypes: float64(1), int64(3)
memory usage: 134.3 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200000 entries, 0 to 2199999
Data columns (total 4 columns):
unique_id    object
row_id       int64
well_id      int64
GR           float64
dtypes: float64(1), int64(2), object(1)
memory usage: 67.1+ MB


(None, None)

In [11]:
df1['label'].value_counts()

0    2313281
2     525376
3     522140
1     520744
4     518459
Name: label, dtype: int64

In [5]:
x_train=df1.drop('label',axis=1)

In [6]:
y_train=df1['label']

In [7]:
x_test=df2.drop('unique_id',axis=1)

In [15]:
y_test=df2['unique_id']

In [16]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((4400000, 3), (4400000,), (2200000, 3), (2200000,))

In [16]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr=LogisticRegression()

In [12]:
lr.fit(x_train,y_train)

C:\Users\hp\Anaconda3\3.7\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\hp\Anaconda3\3.7\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [ ]:
lr_pred=lr.predict(x_test)

In [ ]:
lr.score(x_train,y_train)*100

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
rf=RandomForestClassifier(n_estimators=300,max_depth=7,min_samples_leaf=5,class_weight='balanced',random_state=69)

In [28]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=7, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=300, n_jobs=None, oob_score=False,
            random_state=69, verbose=0, warm_start=False)

In [31]:
train_pred=rf.predict(x_train)

In [32]:
from sklearn.metrics import classification_report,confusion_matrix

In [33]:
print(confusion_matrix(y_train,train_pred))

[[2205688     406       5   81393   25789]
 [  96677   53572  264418   75400   30677]
 [     98   40532  468280   10988    5478]
 [ 176955   47976  149727  108537   38945]
 [ 178440   48263  147401   98301   46054]]


In [29]:
rf_pred=rf.predict(x_test)

In [30]:
rf.score(x_train,y_train)*100

65.50297727272726

In [36]:
CAX_LogFacies_Submission_File['label']=rf_pred

In [37]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn = KNeighborsClassifier(n_neighbors=5)

In [37]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [38]:
knn_pred=knn.predict(x_test)

In [39]:
knn.score(x_train,y_train)

0.8448913636363636

In [40]:
CAX_LogFacies_Submission_File['label']=knn_pred

In [41]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [42]:
from sklearn.ensemble import AdaBoostClassifier

In [43]:
aclf = AdaBoostClassifier(n_estimators=600)

In [44]:
aclf.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=600, random_state=None)

In [45]:
aclf_pred=aclf.predict(x_test)

In [46]:
aclf.score(x_train,y_train)

0.6619818181818182

In [56]:
CAX_LogFacies_Submission_File['label']=aclf_pred

In [57]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [47]:
from sklearn.ensemble import BaggingClassifier

In [122]:
bclf = BaggingClassifier(n_estimators=200,random_state=69)

In [ ]:
bclf.fit(x_train,y_train)

In [ ]:
bclf_pred=bclf.predict(x_test)

In [ ]:
bclf.score(x_train,y_train)

In [57]:
CAX_LogFacies_Submission_File['label']=bclf_pred

In [58]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [11]:
from sklearn.ensemble import GradientBoostingClassifier

In [53]:
gclf = GradientBoostingClassifier(n_estimators=3000,verbose=True,min_samples_leaf=5)

In [54]:
gclf.fit(x_train,y_train)

      Iter       Train Loss   Remaining Time 
         1     6039653.7575         1943.31m
         2     5648431.2906         1955.64m
         3     5343348.2566         1949.49m
         4     5100947.3158         1953.19m
         5     4905114.7557         1963.71m
         6     4745621.2861         1952.47m
         7     4615877.1797         1952.05m
         8     4507781.0528         1954.05m
         9     4419639.2852         1946.81m
        10     4344380.4813         1954.15m
        20     4001967.4431         1948.44m
        30     3906882.1284         1921.69m
        40     3860623.9863         1903.15m
        50     3831693.6294         1894.14m
        60     3816241.3107         1879.59m
        70     3808747.8700         1864.00m
        80     3800847.3686         1854.47m
        90     3795253.4437         1843.27m
       100     3790753.3593         1833.31m
       200     3762809.5823         1755.89m
       300     3741509.8259         1691.31m
       40

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=5, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=3000,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=True, warm_start=False)

In [55]:
gclf_pred=gclf.predict(x_test)

In [56]:
gclf.score(x_train,y_train)

0.7102402272727273

In [63]:
CAX_LogFacies_Submission_File['label']=gclf_pred

In [64]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [8]:
import xgboost
xgb=xgboost.XGBClassifier( max_depth=4,
    learning_rate=0.001,
    n_estimators=5000,
    min_child_weight=6,                      
    verbosity=1,
    silent=None,
    booster='gbtree',
    n_jobs=1,
)

In [9]:
xgb.fit(x_train,y_train)

[10:14:28] WARNING: src/learner.cc:686: Tree method is automatically selected to be 'approx' for faster speed. To use old behavior (exact greedy algorithm on single machine), set tree_method to 'exact'.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0,
       learning_rate=0.001, max_delta_step=0, max_depth=4,
       min_child_weight=6, missing=None, n_estimators=5000, n_jobs=1,
       nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=None, subsample=1, verbosity=1)

In [11]:
xgb_pred=xgb.predict(x_test)

In [ ]:
xgb.score(x_train,y_train)

In [ ]:
CAX_LogFacies_Submission_File['label']=xgb_pred

In [ ]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [23]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
random_cv=RandomizedSearchCV(estimator=xgb,
           param_distributions=hyperparameter_grid,
            cv=5,n_iter=50,
            scoring=None,n_jobs=4,
            verbose=5,
            return_train_score=True,
            random_state=42)

In [37]:
random_cv.fit(x_train,y_train)

C:\Users\hp\Anaconda3\3.7\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 4 is smaller than n_iter=50. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.


TypeError: 'list' object cannot be interpreted as an integer

In [35]:
max_depth=[2,3,5,10,15],
learning_rate=[0.05,0.1,0.15,0.20],
n_estimators=[100,500,900,1100,1500],
min_child_weight=[1,2,3,4],
booster='gbtree',
base_score=[0.25,0.5,0.75,1]
# hyper parameter search

hyperparameter_grid={'max_depth':max_depth,
    'learning_rate':learning_rate,
    'n_estimators':n_estimators,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score
                    }

In [ ]:
CAX_LogFacies_Submission_File['label']=xgb_pred

In [ ]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)

In [12]:
import keras

Using TensorFlow backend.


In [88]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

C:\Users\hp\Anaconda3\3.7\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\hp\Anaconda3\3.7\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\hp\Anaconda3\3.7\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout,Activation
from keras.optimizers import SGD
import numpy as np

In [18]:
y_train=keras.utils.to_categorical(np.random.randint(5,size=(4400000,1)),num_classes=5)

In [23]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu', input_dim = 3))
classifier.add(Dropout(0.5))

# Adding the second hidden layer
classifier.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(0.5))

# Adding the output layer
classifier.add(Dense(units = 5, activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'SGD', loss = 'categorical_crossentropy', metrics = ['accuracy'])

sgd=SGD(lr=0.01,decay=1e-6,momentum=0.9,nesterov=True)

In [25]:
classifier.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])

In [26]:
classifier.fit(x_train,y_train,epochs=10,batch_size=15)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
4400000/4400000 [==============================] - 940s 214us/step - loss: 11.4866 - acc: 0.2000
Epoch 2/10
4400000/4400000 [==============================] - 811s 184us/step - loss: 11.4468 - acc: 0.1999
Epoch 3/10
4400000/4400000 [==============================] - 788s 179us/step - loss: 11.4559 - acc: 0.1998
Epoch 4/10
4400000/4400000 [==============================] - 762s 173us/step - loss: 11.4506 - acc: 0.2000
Epoch 5/10
4400000/4400000 [==============================] - 748s 170us/step - loss: 11.4524 - acc: 0.1998
Epoch 6/10
4400000/4400000 [==============================] - 819s 186us/step - loss: 11.4520 - acc: 0.1999
Epoch 7/10
4400000/4400000 [==============================] - 980s 223us/step - loss: 11.4508 - acc: 0.1999
Epoch 8/10
4400000/4400000 [==============================] - 983s 223us/step - loss: 11.4529 - acc: 0.1997
Epoch 9/10
4400000/4400000 [==============================] - 983s 223us/step - loss: 11

In [35]:
y_pred = classifier.predict(x_test)>0.5

In [37]:
y_pred

array([[False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       ...,
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [38]:
CAX_LogFacies_Submission_File['label']=y_pred

In [39]:
CAX_LogFacies_Submission_File['label']

0          False
1          False
2          False
3          False
4          False
5          False
6          False
7          False
8          False
9          False
10         False
11         False
12         False
13         False
14         False
15         False
16         False
17         False
18         False
19         False
20         False
21         False
22         False
23         False
24         False
25         False
26         False
27         False
28         False
29         False
           ...  
2199970    False
2199971    False
2199972    False
2199973    False
2199974    False
2199975    False
2199976    False
2199977    False
2199978    False
2199979    False
2199980    False
2199981    False
2199982    False
2199983    False
2199984    False
2199985    False
2199986    False
2199987    False
2199988    False
2199989    False
2199990    False
2199991    False
2199992    False
2199993    False
2199994    False
2199995    False
2199996    False
2199997    Fal

In [38]:
CAX_LogFacies_Submission_File.to_csv('C:\\Users\\hp\\Downloads\\CAX_LogFacies_Submission_File.csv',index=False)